# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_start_confirm(object):
    def setupUi(self, Dialog_start_confirm):
        Dialog_start_confirm.setObjectName("Dialog_start_confirm")
        Dialog_start_confirm.resize(400, 300)
        Dialog_start_confirm.setSizeGripEnabled(False)
        Dialog_start_confirm.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_start_confirm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_start_confirm)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget_out_confirm = QtWidgets.QListWidget(Dialog_start_confirm)
        self.listWidget_out_confirm.setObjectName("listWidget_out_confirm")
        self.verticalLayout.addWidget(self.listWidget_out_confirm)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_start_confirm)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_start_confirm)
        QtCore.QMetaObject.connectSlotsByName(Dialog_start_confirm)

    def retranslateUi(self, Dialog_start_confirm):
        _translate = QtCore.QCoreApplication.translate
        Dialog_start_confirm.setWindowTitle(_translate("Dialog_start_confirm", "Dialog"))
        self.label.setText(_translate("Dialog_start_confirm", "需要批量执行的命令如下，请检查后继续"))
